// Rótulos de cada casilla, transcritos del formulario oficial DGII
// (IT-1-2020.xls) — sirven para que la pantalla y el Excel/PDF digan
// exactamente lo mismo que el papel, no una paráfrasis.

export const LABELS_IT1: Record<number, string> = {
  1:  'Total de Operaciones del Período',
  2:  'Exportación de Bienes (Art. 342)',
  3:  'Exportación de Servicios (Art. 344 / Art. 14 lit. j)',
  4:  'Ventas Locales de Bienes o Servicios Exentos (Art. 343 y 344)',
  5:  'Ventas de Bienes o Servicios Exentos por Destino',
  6:  'No Sujetas a ITBIS por Servicios de Construcción',
  7:  'No Sujetas a ITBIS por Comisiones',
  8:  'Ventas Locales de Bienes Exentos (Párrafos III y IV, Art. 343)',
  9:  'Total Ingresos por Operaciones No Gravadas',
  10: 'Total Ingresos por Operaciones Gravadas',
  11: 'Operaciones Gravadas al 18%',
  12: 'Operaciones Gravadas al 16%',
  13: 'Operaciones Gravadas al 9% (Ley 690-16)',
  14: 'Operaciones Gravadas al 8% (Ley 690-16)',
  15: 'Operaciones Gravadas — Venta de Activos Depreciables (Cat. 2 y 3)',
  16: 'ITBIS Cobrado (18% de la casilla 11)',
  17: 'ITBIS Cobrado (16% de la casilla 12)',
  18: 'ITBIS Cobrado (9% de la casilla 13)',
  19: 'ITBIS Cobrado (8% de la casilla 14)',
  20: 'ITBIS Cobrado — Venta de Activos Depreciables',
  21: 'Total ITBIS Cobrado',
  22: 'ITBIS Pagado en Compras Locales',
  23: 'ITBIS Pagado por Servicios Deducibles',
  24: 'ITBIS Pagado en Importaciones',
  25: 'Total ITBIS Deducible',
  26: 'Impuesto a Pagar',
  27: 'Saldo a Favor',
  28: 'Saldos Compensables Autorizados / Reembolsos',
  29: 'Saldo a Favor Anterior',
  30: 'Total Pagos Computables por Retenciones',
  31: 'Otros Pagos Computables a Cuenta',
  32: 'Compensaciones y/o Reembolsos Autorizados',
  33: 'Diferencia a Pagar',
  34: 'Nuevo Saldo a Favor',
  35: 'Recargos',
  36: 'Interés Indemnizatorio',
  37: 'Sanciones',
  38: 'Total a Pagar',
};

export const LABELS_ANEXO_A: Record<number, string> = {
  1:  'Comprobantes Válido para Crédito Fiscal (01 y 31)',
  2:  'Comprobantes Consumo (02 y 32)',
  3:  'Comprobantes Nota de Débito (03 y 33)',
  4:  'Comprobantes Nota de Crédito (04 y 34)',
  5:  'Comprobantes Registro Único de Ingresos (12)',
  6:  'Comprobantes Régimen Especial (14 y 44)',
  7:  'Comprobantes Gubernamentales (15 y 45)',
  8:  'Comprobantes para Exportaciones (16 y 46)',
  9:  'Otras Operaciones (Positivas)',
  10: 'Otras Operaciones (Negativas)',
  11: 'Total Operaciones',
  12: 'Efectivo',
  13: 'Cheque / Transferencia',
  14: 'Tarjeta Débito / Crédito',
  15: 'A Crédito',
  16: 'Bonos o Certificado de Regalo',
  17: 'Permutas',
  18: 'Otras Formas de Venta',
  19: 'Total Operaciones por Tipo de Venta',
  20: 'Ingresos por Operaciones (No Financieros)',
  21: 'Ingresos Financieros',
  22: 'Ingresos Extraordinarios',
  23: 'Ingresos por Arrendamientos',
  24: 'Ingresos por Venta de Activos Depreciables',
  25: 'Otros Ingresos',
  26: 'Total por Tipo de Ingreso',
  45: 'No Deducible — Productores de Bienes/Servicios Exentos',
  46: 'No Deducible — Activos Categoría I',
  47: 'Otros ITBIS Pagados No Deducibles',
  48: 'Total ITBIS No Deducible',
  49: 'Deducible — Bienes Exportados',
  50: 'Deducible — Bienes Gravados',
  51: 'Deducible — Servicios Gravados',
  52: 'Total ITBIS Deducible No Sujeto a Proporcionalidad',
  53: 'ITBIS Sujeto a Proporcionalidad',
  54: 'Coeficiente de Proporcionalidad (%)',
  55: 'ITBIS Admitido por Aplicación de Proporcionalidad',
  56: 'Total ITBIS Deducible',
};
